#include "game_input.h"
#include "input_map.h"

#include <SDL3/SDL_gamepad.h>
#include <SDL3/SDL_scancode.h>

#include <ayther/engine/input.hpp>

#include <chrono>
#include <cstddef>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <optional>
#include <string>
#include <string_view>

namespace {

int passed = 0;
int failed = 0;

void check(const bool condition, const char* description) {
    if (condition) {
        ++passed;
    } else {
        ++failed;
    }
    std::printf("  [%s] %s\n", condition ? " OK " : "FAIL", description);
}

class TempDirectory final {
public:
    TempDirectory() {
        const auto suffix = std::chrono::steady_clock::now()
                                .time_since_epoch()
                                .count();
        path_ = std::filesystem::temp_directory_path() /
                ("ayther-input-map-tests-" + std::to_string(suffix));
        std::filesystem::create_directories(path_);
    }

    ~TempDirectory() {
        std::error_code ignored;
        std::filesystem::remove_all(path_, ignored);
    }

    TempDirectory(const TempDirectory&) = delete;
    TempDirectory& operator=(const TempDirectory&) = delete;

    [[nodiscard]] std::filesystem::path write(const std::string_view name,
                                              const std::string_view contents) const {
        const std::filesystem::path file_path = path_ / name;
        std::ofstream file{file_path, std::ios::binary};
        file.write(contents.data(), static_cast<std::streamsize>(contents.size()));
        return file_path;
    }

    [[nodiscard]] std::filesystem::path child(const std::string_view name) const {
        return path_ / name;
    }

private:
    std::filesystem::path path_;
};

void expect_error(const ayther::InputMapLoadResult& loaded,
                  const ayther::InputMapErrorCode expected,
                  const char* description) {
    const ayther::InputMapError* error = loaded.error();
    check(error != nullptr, description);
    if (error == nullptr) {
        return;
    }
    check(error->code == expected, "input-map error has the expected typed code");
    check(!ayther::describe(*error).empty(),
          "input-map error has a human-readable diagnostic");
}

std::size_t keyboard_index(const ayther::InputMap& map,
                           const ayther::engine::JoypadButton action) {
    const auto bindings = map.keyboard_bindings();
    for (std::size_t index = 0; index < bindings.size(); ++index) {
        if (bindings[index].action == action) {
            return index;
        }
    }
    return bindings.size();
}

std::size_t gamepad_index(const ayther::InputMap& map,
                          const ayther::engine::JoypadButton action) {
    const auto bindings = map.gamepad_bindings();
    for (std::size_t index = 0; index < bindings.size(); ++index) {
        if (bindings[index].action == action) {
            return index;
        }
    }
    return bindings.size();
}

}  // namespace

int main() {
    using ayther::engine::JoypadButton;

    std::printf("== input_map_test ==\n");
    const TempDirectory temp;

    {
        const ayther::InputMap map = ayther::InputMap::defaults();
        check(map.keyboard_scancode(JoypadButton::b) == SDL_SCANCODE_Z,
              "default keyboard B remains Z");
        check(map.keyboard_scancode(JoypadButton::select) == SDL_SCANCODE_RSHIFT,
              "default keyboard Select remains Right Shift");
        check(map.gamepad_button(JoypadButton::b) == SDL_GAMEPAD_BUTTON_SOUTH,
              "default gamepad B remains south");
        check(!map.gamepad_button(JoypadButton::up).has_value(),
              "gamepad directions remain fixed and non-remappable");
        check(map.legacy_select_backspace(),
              "no custom map preserves the legacy Backspace Select alias");
        check(ayther::input_action_key(JoypadButton::start) == "start",
              "RetroPad actions expose the stable input-map key");
    }

    constexpr std::string_view play_map = R"toml(
[keyboard]
up = "Up"
down = "Down"
left = "Left"
right = "Right"
b = "K"
a = "X"
y = "A"
x = "S"
l = "Q"
r = "W"
start = "Return"
select = "Right Shift"

[gamepad]
b = "north"
a = "east"
y = "west"
x = "south"
l = "leftshoulder"
r = "rightshoulder"
start = "start"
select = "back"
)toml";

    {
        const auto loaded = ayther::load_input_map(temp.write("play.toml", play_map));
        check(loaded.map() != nullptr, "the complete map generated by Play loads");
        if (const ayther::InputMapError* error = loaded.error()) {
            std::printf("       diagnostic: %s\n", ayther::describe(*error).c_str());
        }
        if (const ayther::InputMap* map = loaded.map()) {
            check(map->keyboard_scancode(JoypadButton::b) == SDL_SCANCODE_K,
                  "custom keyboard binding resolves through SDL names");
            check(map->gamepad_button(JoypadButton::b) ==
                      SDL_GAMEPAD_BUTTON_NORTH,
                  "custom gamepad binding resolves through contract names");
            check(!map->legacy_select_backspace(),
                  "a supplied map uses only its declared Select binding");

            ayther::MappedInputState snapshot;
            const std::size_t keyboard_b = keyboard_index(*map, JoypadButton::b);
            const std::size_t gamepad_a = gamepad_index(*map, JoypadButton::a);
            snapshot.keyboard.at(keyboard_b) = true;
            snapshot.gamepad.at(gamepad_a) = true;
            snapshot.dpad_up = true;
            const ayther::engine::InputState state =
                ayther::compose_input_state(*map, snapshot);
            check(state.pressed(JoypadButton::b) &&
                      state.pressed(JoypadButton::a) &&
                      state.pressed(JoypadButton::up),
                  "keyboard, remapped gamepad, and fixed directions are OR-ed");

            ayther::MappedInputState analog_snapshot;
            analog_snapshot.left_x = 16000;
            analog_snapshot.left_y = -16001;
            const ayther::engine::InputState analog_state =
                ayther::compose_input_state(*map, analog_snapshot);
            check(!analog_state.pressed(JoypadButton::right) &&
                      analog_state.pressed(JoypadButton::up),
                  "the analog deadzone boundary is deterministic");
        }
    }

    {
        const auto loaded = ayther::load_input_map(
            temp.write("partial.toml", "[keyboard]\nb = \"K\"\n"));
        check(loaded.map() != nullptr, "a partial map inherits defaults");
        if (const ayther::InputMap* map = loaded.map()) {
            check(map->keyboard_scancode(JoypadButton::b) == SDL_SCANCODE_K &&
                      map->keyboard_scancode(JoypadButton::a) == SDL_SCANCODE_X,
                  "partial keyboard overrides preserve untouched actions");
        }
    }

    expect_error(ayther::load_input_map(temp.child("missing.toml")),
                 ayther::InputMapErrorCode::io_error,
                 "a missing input map is rejected");
    expect_error(ayther::load_input_map(
                     temp.write("syntax.toml", "[keyboard\nb = \"K\"\n")),
                 ayther::InputMapErrorCode::parse_error,
                 "malformed TOML is rejected");
    expect_error(ayther::load_input_map(
                     temp.write("unknown-section.toml", "[mouse]\na = \"left\"\n")),
                 ayther::InputMapErrorCode::unknown_section,
                 "unknown top-level sections are rejected");
    expect_error(ayther::load_input_map(
                     temp.write("unknown-action.toml", "[keyboard]\nfire = \"F\"\n")),
                 ayther::InputMapErrorCode::unknown_action,
                 "unknown action keys are rejected");
    expect_error(ayther::load_input_map(
                     temp.write("wrong-type.toml", "[keyboard]\na = 7\n")),
                 ayther::InputMapErrorCode::invalid_value_type,
                 "non-string bindings are rejected");
    expect_error(ayther::load_input_map(
                     temp.write("bad-key.toml", "[keyboard]\na = \"Not a key\"\n")),
                 ayther::InputMapErrorCode::invalid_keyboard_name,
                 "unknown SDL scancode names are rejected");
    expect_error(ayther::load_input_map(
                     temp.write("bad-button.toml", "[gamepad]\na = \"paddle42\"\n")),
                 ayther::InputMapErrorCode::invalid_gamepad_name,
                 "unknown gamepad contract names are rejected");
    expect_error(ayther::load_input_map(
                     temp.write("gamepad-direction.toml", "[gamepad]\nup = \"south\"\n")),
                 ayther::InputMapErrorCode::unsupported_gamepad_action,
                 "gamepad directions cannot be remapped");
    expect_error(ayther::load_input_map(
                     temp.write("duplicate-key.toml", "[keyboard]\nb = \"X\"\n")),
                 ayther::InputMapErrorCode::duplicate_keyboard_binding,
                 "a partial map cannot duplicate an inherited keyboard binding");
    expect_error(ayther::load_input_map(
                     temp.write("duplicate-button.toml", "[gamepad]\nb = \"east\"\n")),
                 ayther::InputMapErrorCode::duplicate_gamepad_binding,
                 "a partial map cannot duplicate an inherited gamepad binding");

    std::printf("\n%d passed, %d failed\n", passed, failed);
    return failed == 0 ? 0 : 1;
}
