file(MAKE_DIRECTORY "${TEST_DIR}")
file(WRITE "${TEST_DIR}/invalid.toml" "version = [")
file(WRITE "${TEST_DIR}/fixture.rom" "TEST ROM")
function(expect_failure expected reason)
    execute_process(COMMAND "${RUNTIME_EXE}" --core "${CORE}" --rom fixture.rom ${ARGN}
        WORKING_DIRECTORY "${TEST_DIR}" RESULT_VARIABLE result
        OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
    if(NOT "${result}" STREQUAL "${expected}" OR NOT output MATCHES "${reason}")
        message(FATAL_ERROR "Expected ${expected}/${reason}; got ${result}: ${output}\n${error}")
    endif()
    if(output MATCHES "Session ready|AYTHER_STATUS.*\"event\":\"ready\"|frames .* reached")
        message(FATAL_ERROR "Failed pack was reported ready: ${output}")
    endif()
endfunction()
expect_failure(64 "cli.invalid_argument" --trust-registry)
expect_failure(78 "pack.trust_registry_invalid" --trust-registry missing.toml)
expect_failure(78 "pack.trust_registry_invalid" --trust-registry invalid.toml)
expect_failure(78 "pack.trust_registry_invalid" --trust-registry "${TEST_DIR}")
expect_failure(4 "pack.open_failed" --pack missing.ay)
foreach(registry unknown revoked expired future wrong-game)
    expect_failure(4 "pack.open_failed" --pack "${FIXTURES}/valid.ay" --trust-registry "${FIXTURES}/${registry}.toml")
endforeach()
foreach(pack tampered unsigned development incompatible)
    expect_failure(4 "pack.open_failed" --pack "${FIXTURES}/${pack}.ay" --trust-registry "${FIXTURES}/valid.toml")
endforeach()
file(COPY "${FIXTURES}/valid.toml" DESTINATION "${TEST_DIR}")
execute_process(COMMAND "${RUNTIME_EXE}" --core "${CORE}" --rom fixture.rom
    --pack "${FIXTURES}/valid.ay" --trust-registry valid.toml --frames 3 --saves-dir "${TEST_DIR}/saves"
    WORKING_DIRECTORY "${TEST_DIR}" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
if(NOT result EQUAL 0 OR NOT output MATCHES "has_pack=1" OR NOT output MATCHES "--frames 3 reached")
    message(FATAL_ERROR "Trusted CLI launch failed: ${result}: ${output}\n${error}")
endif()
